# Generated by Django 6.0.5 on 2026-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['game', '-score'], name='leaderboard_game_id_e4d31f_idx'),
        ),
    ]
