# Generated by Django 6.0.5 on 2026-05-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0002_score_leaderboard_game_id_e4d31f_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="score",
            options={"ordering": ["-score", "date_saved"]},
        ),
        migrations.RemoveIndex(
            model_name="score",
            name="leaderboard_game_id_e4d31f_idx",
        ),
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.BigIntegerField(),
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["game", "-score", "date_saved"],
                name="leaderboard_game_id_252262_idx",
            ),
        ),
    ]
